permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "/nandomoreira-jekyll-theme" # change to empty string ""
# domain_name: nandomoreira.me


source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Harrisburg University SGA
title: HU SGA
description: "A organization devoted to the students of Harrisburg University"
meta_description: "A organization devoted to the students of Harrisburg University"
meta_keywords: "Harrisburg, Harrisburg University, hu, SGA"
url: http://nandomoreira.me
production_url: http://nandomoreira.me
repo: https://github.com/husga/website
# disqus_shortname: "fernandomoreira"
rss_path: source/
author:
  name      : HU SGA
  image     : /assets/images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://sga.harrisburgu.edu
  facebook  : http://www.facebook.com/groups/171811932864425/
  # twitter   : http://twitter.com/nandomoreirame
  # instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/husga
  # linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /nandomoreira-jekyll-theme/assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
