# Site settings
title: Student Government

# Social
github   : github.com/husga
facebook : http://www.facebook.com/groups/171811932864425/
email    : sga@my.harrisburgu.edu


# Build settings
markdown: kramdown
rouge : pygments

comments: true

destination: _site

# SEO settings
description: "A Government for the STUDENTS by the STUDENTS"
keywords: "SEO, Austin Barrett, Software, Art, Graphic Design, Geek Tricks"
url: http://sga.harrisburgu.edu
baseurl: "/website"
# baseurl: "/austinisaninja"


# disqus_shortname: "fernandomoreira"
